# chart-testing (ct) configuration
# https://github.com/helm/chart-testing

# Target branches for detecting changed charts
target-branch: main
remote: origin

# Chart directories to process
chart-dirs:
  - .

# Chart repositories (required for dependencies)
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami

# Charts to exclude from testing
excluded-charts: []

# Helm version to use
helm-version: v3.14.0

# Enable chart schema validation
validate-chart-schema: true

# Enable values schema validation (values.schema.json)
validate-maintainers: false

# Check version increments
check-version-increment: true

# Upgrade testing
upgrade: false  # Will enable in separate upgrade test job

# Additional Helm install arguments
# Timeout increased to 15min for CI environment (PostgreSQL + Heimdall startup)
helm-extra-args: --timeout 900s

# Namespace for chart installation
# NOTE: Do NOT set a fixed namespace. Chart-testing needs to create random
# namespaces for each test to ensure isolation and proper cleanup.
# When namespace is empty, ct automatically creates/deletes test namespaces.

# Release name
release-label: app.kubernetes.io/instance
