{{- if not .Values.heimdall.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . }}-secrets
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- /*
  Three-approach secrets management (following Vulcan chart pattern):
  Priority order: existingSecret > inline secrets > secretsFiles

  Approach 1: Use existing secret (production with External Secrets Operator, Sealed Secrets, Vault)
  heimdall:
    existingSecret: "heimdall-production-secrets"

  Approach 2: File-based secrets (development - default, gitignored)
  heimdall:
    secretsFiles: ["env/heimdall-secrets.yaml"]
  Generate with: ./generate-heimdall-secrets.sh

  Approach 3: Inline secrets (CI/CD)
  heimdall:
    secrets:
      jwtSecret: "..."
      adminPassword: "..."
  */ -}}

  {{- /* Approach 3: Inline secrets from values.yaml */ -}}
  {{- if .Values.heimdall.secrets }}
    {{- range $key, $val := .Values.heimdall.secrets }}
  {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}

  {{- /* Approach 2: File-based secrets (default for development) */ -}}
  {{- if .Values.heimdall.secretsFiles }}
    {{- range $path := .Values.heimdall.secretsFiles }}
      {{- $fileContent := $.Files.Get $path }}
      {{- if $fileContent }}
        {{- $lines := splitList "\n" $fileContent }}
        {{- range $line := $lines }}
          {{- /* Skip empty lines and comments */ -}}
          {{- if and $line (not (hasPrefix "#" $line)) }}
            {{- $parts := splitList ": " $line }}
            {{- if eq (len $parts) 2 }}
  {{ index $parts 0 }}: {{ index $parts 1 | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- /* Fallback defaults for required secrets (ONLY if neither approach 2 nor 3 provided them) */ -}}
  {{- if not (or .Values.heimdall.secrets .Values.heimdall.secretsFiles) }}
    {{- /* These are INSECURE defaults for quickstart only */ -}}
    {{- /* WARNING: Generate proper secrets with ./generate-heimdall-secrets.sh before production use */ -}}
  jwtSecret: "INSECURE_DEFAULT_CHANGE_ME_{{ randAlphaNum 64 }}"
  adminPassword: "Admin123!_CHANGE_ME"
  databasePassword: "postgres_{{ randAlphaNum 16 }}"
  {{- end }}
{{- end }}
