{{- if .Values.heimdall.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heimdall.serviceAccountName" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
  {{- with .Values.heimdall.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
