apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
    app.kubernetes.io/component: heimdall
spec:
  serviceName: {{ template "heimdall.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "heimdall.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: heimdall
  template:
    metadata:
      {{- with .Values.heimdall.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "heimdall.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: heimdall
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.heimdall.podSecurityContext | nindent 8 }}
      {{- if .Values.extraCertificates.enabled }}
      initContainers:
        - name: concat-ca-certs
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              # Concatenate all CA certificates from ConfigMap into single bundle file
              cat /tmp/ca-source/*.crt /tmp/ca-source/*.pem > /tmp/ca-certs/ca-bundle.pem 2>/dev/null || true
              echo "CA bundle created with $(grep -c 'BEGIN CERTIFICATE' /tmp/ca-certs/ca-bundle.pem 2>/dev/null || echo 0) certificate(s)"
          volumeMounts:
            - name: ca-certificates-source
              mountPath: /tmp/ca-source
              readOnly: true
            - name: ca-certificates
              mountPath: /tmp/ca-certs
      {{- end }}
      volumes:
        - name: yarn-cache
          emptyDir: {}
        - name: yarn-tmp
          emptyDir: {}
        {{- if .Values.extraCertificates.enabled }}
        - name: ca-certificates-source
          configMap:
            name: {{ .Values.extraCertificates.configMapName | default (printf "%s-ca-certs" (include "heimdall.fullname" .)) }}
        - name: ca-certificates
          emptyDir: {}
        {{- end }}
      containers:
        - name: heimdall-front
          securityContext:
            {{- toYaml .Values.heimdall.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.heimdall.resources | nindent 12 }}
          image: "{{ .Values.heimdall.image.repository }}:{{ .Values.heimdall.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.heimdall.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: yarn-cache
              mountPath: /home/node/.cache
            - name: yarn-tmp
              mountPath: /tmp
            {{- if .Values.extraCertificates.enabled }}
            - name: ca-certificates
              mountPath: /usr/local/share/ca-certificates
              readOnly: true
            {{- end }}
          # ===================================================================
          # Environment Variables - Load from ConfigMap and Secret
          # ===================================================================
          # Following Vulcan pattern: use envFrom for bulk loading, env for overrides
          envFrom:
          - configMapRef:
              name: {{ include "heimdall.fullname" . }}-config
          - secretRef:
              name: {{ ternary .Values.heimdall.existingSecret (printf "%s-secrets" (include "heimdall.fullname" .)) (not (empty .Values.heimdall.existingSecret)) }}
          env:
          {{- if .Values.extraCertificates.enabled }}
          - name: NODE_EXTRA_CA_CERTS
            value: /usr/local/share/ca-certificates/ca-bundle.pem
          {{- end }}
          # DATABASE_PASSWORD injection based on deployment pattern
          # Pattern 1: Embedded PostgreSQL - reference Bitnami's secret
          {{- if .Values.postgresql.enabled }}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "heimdall.databaseSecretName" . }}
                key: {{ include "heimdall.databaseSecretKey" . }}
          {{- else if .Values.externalDatabase.existingSecret }}
          # Pattern 2: External DB with existing secret
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externalDatabase.existingSecret }}
                key: {{ .Values.externalDatabase.existingSecretPasswordKey | default "password" }}
          {{- end }}
          # Pattern 3: External DB without existing secret - comes from envFrom heimdall-secrets above
          livenessProbe:
            {{- with .Values.heimdall.livenessProbe }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}

          readinessProbe:
            {{- with .Values.heimdall.readinessProbe }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
      {{- with .Values.heimdall.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.heimdall.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.heimdall.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
