apiVersion: v1
kind: Secret
metadata:
  name: {{ template "heimdall.fullname" . }}
  labels:
    {{ include "heimdall.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if .Values.databaseUsername }}
  databaseUsername: {{ .Values.databaseUsername | quote }}
  {{ end }}

  {{ if .Values.databaseSsl = True}} ##If Database SSL = True, then use conditional
  databaseSslKey: {{ .Values.databaseSslKey | quote }}
  {{ end }}
  {{ if .Values.databaseSsl = True}}
  databaseSslCert: {{ .Values.databaseSslCert | quote }}
  {{ end }}
  {{ if .Values.databaseSsl = True}}
  databaseSslCa: {{ .Values.databaseSslCa | quote }}
  {{ end }}

  jwtSecret: {{ .Values.jwtSecret | quote }}

  {{ if .Values.apiKeySecret }}
  apiKeySecret: {{ .Values.apiKeySecret | quote }}
  {{ end }}

  {{ if .Values.adminPassword }}
  adminPassword: {{ .Values.adminPassword | quote }}
  {{ end }}

  {{ if .Values.githubClientId }} 
  githubClientId: {{ .Values.githubClientId | quote }}
  {{ end }}
  {{ if .Values.githubClientId }} ##If client ID Supplied, then use conditional
  githubClientSecret: {{ .Values.githubClientSecret | quote }}
  {{ end }}

  {{ if .Values.gitlabClientId }}
  gitlabClientId: {{ .Values.gitlabClientId | quote }}
  {{ end }}
  {{ if .Values.gitlabClientId }} ##If client ID Supplied, then use conditional
  gitlabClientSecret: {{ .Values.gitlabClientSecret | quote }}
  {{ end }}

  {{ if .Values.googleClientId }} 
  googleClientId: {{ .Values.googleClientId | quote }}
  {{ end }}
  {{ if .Values.googleClientId }} ##If client ID Supplied, then use conditional
  googleClientSecret: {{ .Values.googleClientSecret | quote }}
  {{ end }}

  {{ if .Values.oktaClientId }}
  oktaClientId: {{ .Values.oktaClientId | quote }}
  {{ end }}
  {{ if .Values.oktaClientId }} ##If client ID Supplied, then use conditional
  oktaClientSecret: {{ .Values.oktaClientSecret | quote }}
  {{ end }}
  {{ if .Values.oidcClientId }}
  oidcClientId: {{ .Values.oidcClientId | quote }}
  {{ end }}
  {{ if .Values.oidcClientId }}   ##If client ID Supplied, then use conditional
  oidcClientSecret: {{ .Values.oidcClientSecret | quote }}
  {{ end }}

  {{ if .Values.ldapEnabled = True }} ##Same with SSL
  ldapBindDn: {{ .Values.ldapBindDn | quote }}
  {{ end }}
  {{ if .Values.ldapEnabled = True }}
  ldapPassword: {{ .Values.ldapPassword | quote }}
  {{ end }}
  {{ if .Values.ldapEnabled = True }}
  ldapSslCa: {{ .Values.ldapSslCa | quote }}
  {{ end }}
data:
  {{ if .Values.databasePassword }}
  databasePassword: {{ .Values.databasePassword | b64enc | quote }}
  {{ end }}