apiVersion: v1
kind: Secret
metadata:
  name: {{ template "heimdall.fullname" . }}
  labels:
    {{ include "heimdall.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.databaseUsername }}
  databaseUsername: {{ .Values.databaseUsername | quote }}
  {{- end }}

  {{- if and (eq .Values.databaseSsl true) (.Values.databaseSslKey) }}
  databaseSslKey: {{ .Values.databaseSslKey | quote }}
  {{- end }}
  {{- if and (eq .Values.databaseSsl true) (.Values.databaseSslCert) }}
  databaseSslCert: {{ .Values.databaseSslCert | quote }}
  {{- end }}
  {{- if and (eq .Values.databaseSsl true) (.Values.databaseSslCa) }}
  databaseSslCa: {{ .Values.databaseSslCa | quote }}
  {{- end }}

  jwtSecret: {{ .Values.jwtSecret | quote }}

  {{- if .Values.apiKeySecret }}
  apiKeySecret: {{  .Values.apiKeySecret | quote }}
  {{- end }}

  {{- if .Values.adminPassword }}
  adminPassword: {{ .Values.adminPassword | quote }}
  {{- end }}

  {{- if .Values.githubClientId }} 
  githubClientId: {{ .Values.githubClientId | quote }}
  {{- end }}
  {{- if .Values.githubClientId }}
  githubClientSecret: {{ .Values.githubClientSecret | quote }}
  {{- end }}

  {{- if .Values.gitlabClientId }}
  gitlabClientId: {{ .Values.gitlabClientId | quote }}
  {{- end }}
  {{- if .Values.gitlabClientId }}
  gitlabClientSecret: {{ .Values.gitlabClientSecret | quote }}
  {{- end }}

  {{- if .Values.googleClientId }} 
  googleClientId: {{ .Values.googleClientId | quote }}
  {{- end }}
  {{- if .Values.googleClientId }}
  googleClientSecret: {{ .Values.googleClientSecret | quote }}
  {{- end }}

  {{- if .Values.oktaClientId }}
  oktaClientId: {{ .Values.oktaClientId | quote }}
  {{- end }}
  {{- if .Values.oktaClientId }}
  oktaClientSecret: {{ .Values.oktaClientSecret | quote }}
  {{- end }}
  {{- if .Values.oidcClientId }}
  oidcClientId: {{ .Values.oidcClientId | quote }}
  {{- end }}
  {{- if .Values.oidcClientId }}
  oidcClientSecret: {{ .Values.oidcClientSecret | quote }}
  {{- end }}

  {{- if and (eq .Values.ldapEnabled true) (.Values.ldapBindDn) }}
  ldapBindDn: {{ .Values.ldapBindDn | quote }}
  {{- end }}
  {{- if and (eq .Values.ldapEnabled true) (.Values.ldapPassword) }}
  ldapPassword: {{ .Values.ldapPassword | quote }}
  {{- end }}
  {{- if and (eq .Values.ldapEnabled true) (.Values.ldapSslCa) }}
  ldapSslCa: {{ .Values.ldapSslCa | quote }}
  {{- end }}
data:
  databasePassword: {{ .Values.databasePassword | b64enc | quote }}