{{- if not .Values.sops.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.databaseSslKey }}
  databaseSslKey: {{ .Values.databaseSslKey | quote }}
  {{- end }}
  {{- if .Values.databaseSslCert }}
  databaseSslCert: {{ .Values.databaseSslCert | quote }}
  {{- end }}
  {{- if .Values.databaseSslCa }}
  databaseSslCa: {{ .Values.databaseSslCa | quote }}
  {{- end }}

  jwtSecret: {{ .Values.jwtSecret | quote }}

  {{- if .Values.apiKeySecret }}
  apiKeySecret: {{  .Values.apiKeySecret | quote }}
  {{- end }}

  {{- if .Values.adminPassword }}
  adminPassword: {{ .Values.adminPassword | quote }}
  {{- end }}

  {{- if .Values.githubClientId }} 
  githubClientId: {{ .Values.githubClientId | quote }}
  {{- end }}
  {{- if .Values.githubClientSecret }}
  githubClientSecret: {{ .Values.githubClientSecret | quote }}
  {{- end }}

  {{- if .Values.gitlabClientId }}
  gitlabClientId: {{ .Values.gitlabClientId | quote }}
  {{- end }}
  {{- if .Values.gitlabClientSecret }}
  gitlabClientSecret: {{ .Values.gitlabClientSecret | quote }}
  {{- end }}

  {{- if .Values.googleClientId }} 
  googleClientId: {{ .Values.googleClientId | quote }}
  {{- end }}
  {{- if .Values.googleClientSecret }}
  googleClientSecret: {{ .Values.googleClientSecret | quote }}
  {{- end }}

  {{- if .Values.oktaClientId }}
  oktaClientId: {{ .Values.oktaClientId | quote }}
  {{- end }}
  {{- if .Values.oktaClientSecret }}
  oktaClientSecret: {{ .Values.oktaClientSecret | quote }}
  {{- end }}

  {{- if .Values.oidcClientId }}
  oidcClientId: {{ .Values.oidcClientId | quote }}
  {{- end }}
  {{- if .Values.oidcClientSecret }}
  oidcClientSecret: {{ .Values.oidcClientSecret | quote }}
  {{- end }}

  {{- if eq .Values.ldapBindDn true }}
  ldapBindDn: {{ .Values.ldapBindDn | quote }}
  {{- end }}
  {{- if eq .Values.ldapPassword true }}
  ldapPassword: {{ .Values.ldapPassword | quote }}
  {{- end }}
  {{- if .Values.ldapSslCa }}
  ldapSslCa: {{ .Values.ldapSslCa | quote }}
  {{- end }}
data:
  {{- if .Values.databasePassword }}
  databasePassword: {{ .Values.databasePassword | b64enc | quote }}
  {{- end }}
{{- end }}